### ISSUE TITLE
workLocation page numbers not corresponding in Peking Kangyur 

### ISSUE THREAD

**Issue by berger-n** [buda-base/rKTs-migration#12]
there seem to be a difference between original page numbers
as stated in https://github.com/brunogml/rKTs/blob/master/Kanjur/peking.xml 
and actual page numbers in resource files eg http://library.bdrc.io/show/bdr:W1PD96684_0001, http://library.bdrc.io/show/bdr:W1PD96684_0002, http://library.bdrc.io/show/bdr:W1PD96684_0003...

**Comment by eroux** [comment]
can you give an example? the first seems fine to me... there's a difference between what we record (image number) and what's in the .xml, which are folio numbers. there are two images per folio

**Comment by berger-n** [comment]
this is what I'm looking at:
* http://library.bdrc.io/show/bdr:W1PD96684_0002
"Vol.1 p.4"
![image](https://user-images.githubusercontent.com/33383857/46477881-fcf5a880-c7eb-11e8-8c7d-9c678543b998.png)
* https://github.com/brunogml/rKTs/blob/master/Kanjur/peking.xml#L19
"Vol.1 p.117"
![image](https://user-images.githubusercontent.com/33383857/46477922-1696f000-c7ec-11e8-9f08-72e04d1cc800.png)

**Comment by eroux** [comment]
the data is ok, it's just that the rKTs outlines give folio numbers (1a, 1b, 2a, 2b, 3a, etc.) while our outlines give image numbers (1, 2, 3, 4, etc.)
